
services:

  worker-db:
    image: postgres:15-alpine
    container_name: worker_profile_and_services_service_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1234567"
      POSTGRES_DB: worker_profile_and_services_service_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
